name: Cronycal CI Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WORKING_DIR: src/Cronycal

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Node/NPM/JavaScript checks
      - name: Install markdownlint-cli2 tool via NPM
        run: npm install -g markdownlint-cli2

      - name: Verify markdown formatting with markdownlint
        run: markdownlint-cli2 "**/*.md"

      # C#/.NET checks and builds
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install .NET tools
        run: dotnet tool restore

      - name: Verify C# formatting with CSharpier
        run: dotnet csharpier check .

      - name: Restore dependencies
        run: |
          cd $WORKING_DIR
          echo "Restoring dependencies in $WORKING_DIR"
          dotnet restore

      - name: Build
        run: | 
          cd $WORKING_DIR
          echo "Building project in $WORKING_DIR"
          dotnet build --configuration Release --no-restore

    #   - name: Test
    #     run: |
    #       cd $WORKING_DIR
    #       echo "Running tests in $WORKING_DIR"
    #       dotnet test --configuration Release --no-build --verbosity normal
